spring.application.name=gitpulse
server.port=8080

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600000

github.api.base-url=https://api.github.com
github.api.token=${GITHUB_API_TOKEN}